# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test_eq": "00_core.ipynb",
         "listify": "00_core.ipynb",
         "test_in": "00_core.ipynb",
         "test_err": "00_core.ipynb",
         "configure_logging": "00_core.ipynb",
         "setup_dataframe_copy_logging": "00_core.ipynb",
         "n_total_series": "00_core.ipynb",
         "n_days_total": "00_core.ipynb",
         "raw_dir": "00_core.ipynb",
         "read_series_sample": "00_core.ipynb",
         "melt_sales_series": "00_core.ipynb",
         "extract_day_ids": "00_core.ipynb",
         "join_w_calendar": "00_core.ipynb",
         "join_w_prices": "00_core.ipynb",
         "to_parquet": "00_core.ipynb",
         "extract_id_columns": "00_core.ipynb",
         "get_submission_template_melt": "00_core.ipynb",
         "ParquetIterableDataset": "01_petastorm.ipynb",
         "prepare_data_on_disk": "02_pipeline.ipynb"}

modules = ["core.py",
           "petastorm.py",
           "pipeline.py"]

doc_url = "https://cluePrints.github.io/kaggle_m5_nbdev/"

git_url = "https://github.com/cluePrints/kaggle_m5_nbdev/tree/master/"

def custom_doc_links(name): return None
