# AUTOGENERATED! DO NOT EDIT! File to edit: 02_pipeline.ipynb (unless otherwise specified).

__all__ = ['prepare_data_on_disk']

# Cell

from core import read_series_sample, melt_sales_series, extract_day_ids, join_w_calendar, join_w_prices
from core import to_parquet
import os

def prepare_data_on_disk(log, n_sample_series, processed):
    expected_path = f'{processed}/sales_series_melt.parquet'
    if os.path.exists(expected_path) and not force_data_prep:
        log.info(f'Found parquet file ({expected_path})- skipping the prep')
        return

    log.info(f'Not found parquet file ({expected_path}) - preparing the data')

    sales_series = read_series_sample(log, n_sample_series)
    sales_series = melt_sales_series(sales_series)
    sales_series = extract_day_ids(sales_series)
    sales_series = join_w_calendar(sales_series)
    sales_series = join_w_prices(sales_series).persist()
    to_parquet(sales_series, 'sales_series_melt.parquet', processed, log)